### PR TITLE
Support ActiveRecord 6.1

### PR DESCRIPTION
**Pull request by siav92**
Add support for ActiveRecord 6.1

### CODE REVIEW

**Comment by siav92** [comment]
We have been testing this upgrade internally and have found one PG specific issue. There is [a change in 6.1](https://github.com/rails/rails/commit/71e45582b794d7cdcbd72a93dc2f3c8665859653#diff-e6fd03cad5e3437c76b6c5db106359124dc9feab8341ade39b9ae54af001fac9R59) where they aren't including column types that have been cast by PG anymore. 

As a result. our queries are failing on https://github.com/jhollinger/occams-record/blob/master/lib/occams-record/results/results.rb#L44 because there are no types coming in the ActiveRecord results.

I could use some help/hints for handling this case. 

Our app specs: 
- Rails 6.1.3
- PG 11
- Ruby 2.7.1

**Comment by andreimoment** [comment]
@siav92 I seems I am having the same issue after upgrade to Rails 6.1.3. See https://github.com/jhollinger/occams-record/issues/9

I am wondering, were you able to resolve?

**Comment by jhollinger** [comment]
Closing since support for 6.1 is in the 1.2.x series.

**Comment by siav92** [comment]
@andreimoment Unfortunately not! There is an open Rails PR for this https://github.com/rails/rails/pull/42375 but it hasn't been moving forward.

**Pull request closed without merging**
